name: Terraform Quality Checks

on: [ push, pull_request ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2

      - name: Check documentation
        run: |
          if [ ! -f README.md ]; then
            echo "❌ Missing README.md"
            exit 1
          fi
          if [ ! -f LICENSE ]; then
            echo "❌ Missing LICENSE file"
            exit 1
          fi

      - name: Check file structure
        run: |
          required_files=("main.tf" "variables.tf" "outputs.tf")
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            fi
          done

      - name: Terraform fmt
        run: terraform fmt -check -recursive -diff

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Check for sensitive data
        run: |
          if grep -r --include="*.tf" "password\|secret\|key" .; then
            echo "❌ Potential sensitive data found"
            exit 1
          fi